#ifndef _BULWARK_CURSOR_STYLE_DEFINITIONS_H
#define _BULWARK_CURSOR_STYLE_DEFINITIONS_H

typedef enum BulwarkCursorShape {
  BULWARK_CURSOR_SHAPE_BLOCK,
  BULWARK_CURSOR_SHAPE_I,
  BULWARK_CURSOR_SHAPE_UNDERLINE,
  BULWARK_CURSOR_SHAPE_COUNT
} BulwarkCursorShape;

#endif