#ifndef _BULWARK_COLOR16_DEFINITIONS_H
#define _BULWARK_COLOR16_DEFINITIONS_H

#define BULWARK_COLOR16_BLACK 0
#define BULWARK_COLOR16_RED 1
#define BULWARK_COLOR16_GREEN 2
#define BULWARK_COLOR16_YELLOW 3
#define BULWARK_COLOR16_BLUE 4
#define BULWARK_COLOR16_MAGENTA 5
#define BULWARK_COLOR16_CYAN 6
#define BULWARK_COLOR16_WHITE 7
#define BULWARK_COLOR16_GRAY 8
#define BULWARK_COLOR16_BRIGHT_RED 9
#define BULWARK_COLOR16_BRIGHT_GREEN 10
#define BULWARK_COLOR16_BRIGHT_YELLOW 11
#define BULWARK_COLOR16_BRIGHT_BLUE 12
#define BULWARK_COLOR16_BRIGHT_MAGENTA 13
#define BULWARK_COLOR16_BRIGHT_CYAN 14
#define BULWARK_COLOR16_BRIGHT_WHITE 15

#endif