name: C89 CI

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -H~/ -B~/build
    - name: build
      run: cmake --build ~/build --config MinSizeRel --target all
